os: linux
dist: bionic
language: minimal

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled IMAGE_NAME=a16bitsysop/olefy url=HeinleinSupport/olefy/master/olefy.py

before_script:
  - VER=$(curl -sSI https://raw.githubusercontent.com/$url | grep "^ETag:" | sed -e s+ETag:.W/++g -e s+\"++g)
  - TAG="-t $IMAGE_NAME:$(date +%Y.%m.%d)"
  - MY_VER="$(docker container run --rm olefy cat /etc/githash)"
  - if [ -n "$MY_VER" ] && [ "$MY_VER" = "$VER" ]; then travis_terminate 0; fi
  - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"

script:
  - for i in {1..15}; do sleep 1m; echo "waiting $i mins"; done
  - docker buildx build --platform linux/amd64,linux/386,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7 $TAG -t "$IMAGE_NAME" --push .
