os: linux
dist: bionic
language: minimal

env:
  - DOCKER_CLI_EXPERIMENTAL=enabled IMAGE_NAME=a16bitsysop/olefy url=HeinleinSupport/olefy/master/olefy.py

before_script:
  - VER=$(curl -sSI https://raw.githubusercontent.com/$url | grep "^ETag:" | sed -e s+ETag:.W/++g -e s+\"++g)
  - ALP="$(docker container run --rm alpine cat /etc/alpine-release)"
  - TAG="-t $IMAGE_NAME:$(date +%Y.%m.%d)-alpine$ALP"
  - |
     docker image pull $IMAGE_NAME && MY_VER="$(docker container run --rm $IMAGE_NAME sh -c 'F="/etc/githash"; if [ -f "$F" ]; then cat "$F"; fi')"
     docker image pull $IMAGE_NAME && MY_ALP="$(docker container run --rm $IMAGE_NAME cat /etc/alpine-release)"
     echo "Git    version is $VER"
     echo "Docker version is $MY_VER"
     if [ -z $NOW ] && [ -n "$MY_VER" ] && [ "$MY_VER" = "$VER" ] && [ "$MY_ALP" = "$ALP" ]; then travis_terminate 0; fi
  - curl -fsSL get.docker.com -o get-docker.sh && sh get-docker.sh
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - docker buildx create --use
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

script:
  - if [ -z "$NOW" ]; then for i in {1..15}; do sleep 1m; echo "waiting $i mins"; done; fi
  - docker buildx build --platform linux/amd64,linux/386,linux/ppc64le,linux/s390x,linux/arm64,linux/arm/v7 $TAG -t "$IMAGE_NAME" --push .
