import: a16bitsysop/travis-build-configs:docker-apt.yml

env:
  - IMAGE_NAME=a16bitsysop/olefy url=HeinleinSupport/olefy/master/olefy.py

before_script:
  - ALP_VER=$(version.py -b)
  - VER="$(version.py -g $url)-$ALP_VER"
  - TAG="$(date +%d%m%g)-alpine$ALP_VER"
  - MY_ALP=$(version.py -m $IMAGE_NAME)
  - MY_VER="$(version.py -f $IMAGE_NAME)-$MY_ALP"
  - |
     echo "Checking if update needed..."
     echo "Git    version is $VER"
     echo "Docker version is $MY_VER"
     if [ -z $NOW ] && [ "$MY_VER" = "$VER" ]; then travis_terminate 0; fi

script:
  - docker-test.sh || travis_terminate 1
  - docker-build.sh "$TAG" "$ALP_VER" "$VER"
  - curl -X POST "https://hooks.microbadger.com/images/$IMAGE_NAME/$WEBHOOK"
